sudo: false
language: ruby
cache:
- bundler
rvm:
- 2.4.3
- 2.5.1
before_install:
  - openssl aes-256-cbc -K $encrypted_b73e363d372e_key -iv $encrypted_b73e363d372e_iv -in trusona.key.pem.enc -out trusona.key.pem -d
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec spec -f p
  - bundle exec rubocop lib/**/*.rb -F
  - gem build trusona.gemspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
deploy:
  provider: rubygems
  api_key: $RUBYGEMS_API_KEY
  gem: trusona
  gemspec: trusona.gemspec
  skip_cleanup: true
  on:
    tags: true
    rvm: '2.4.3'
